server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/finance
    username: finance
    password: finance123
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    enabled: true
    table: flyway_schema_history_user

jwt:
  secret: my-super-secret-key-for-jwt-tokens-that-is-at-least-256-bits-long
  expiration-ms: 86400000
